### PR TITLE
Fix #11 - Upgrade mermaid.js to 8.10.1

### LINKED ISSUE #11: Docs render wrong
Hello! 

First of all, *amazing crate* being able to embed diagrams in the documentation is great!

I'm currently building an embedded DSL and part of my functionally is exporting diagrams of several kinds.
Logically, embedding them in the documentation would be the next step and hence I started using aquamarine.

During the process I noticed my diagrams were correct according to the [Live Editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic3RhdGVEaWFncmFtLXYyXG4gICAgWypdIC0tPiBPZmYgOiBzY3Jld1xuICAgIE9mZiAtLT4gWypdIDogdW5zY3Jld1xuICAgIE9mZiAtLT4gT24gOiB0dXJuX29uXG4gICAgT24gLS0-IE9mZiA6IHR1cm5fb2ZmXG4gICAgT24gOiBnZXRfY29sb3JcbiAgICBzdGF0ZSBDX09uIDw8Y2hvaWNlPj5cbiAgICBPbiAtLT4gQ19Pbjogc2V0X2NvbG9yXG4gICAgQ19PbiAtLT4gT2ZmXG4gICAgQ19PbiAtLT4gT25cbiAgICAgICAgICAgICIsIm1lcm1haWQiOnt9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ), but when rendered they would be missing the decision diamond for example.

This is the current renderization:
```rust
#[cfg_attr(doc, ::aquamarine::aquamarine)]
#[doc= "```mermaid"]
#[doc= "stateDiagram-v2"]
#[doc= "  [*] --> AccountValidation : start_transaction"]
#[doc= "  Error --> [*] : finish"]
#[doc= "  Finish --> [*] : finish"]
#[doc= "  state C_Valid <<choice>>"]
#[doc= "  Valid --> C_Valid: perform_transaction"]
#[doc= "  C_Valid --> Error"]
#[doc= "  C_Valid --> Finish"]
#[doc= "  state C_AccountValidation <<choice>>"]
#[doc= "  AccountValidation --> C_AccountValidation: validate_accounts"]
#[doc= "  C_AccountValidation --> Error"]
#[doc= "  C_AccountValidation --> Valid"]
#[doc= "```"]
const WEIRD: i32 = 0;
```

image

I tried upgrading mermaid.js to the newest version and suddenly the diagrams present in `main.rs` work.

```rust
#[cfg_attr(doc, ::aquamarine::aquamarine)]
#[doc= "```mermaid"]
#[doc= "stateDiagram-v2"]
#[doc= "  [*] --> AccountValidation : start_transaction"]
#[doc= "  Error --> [*] : finish"]
#[doc= "  Finish --> [*] : finish"]
#[doc= "  state C_Valid <<choice>>"]
#[doc= "  Valid --> C_Valid: perform_transaction"]
#[doc= "  C_Valid --> Error"]
#[doc= "  C_Valid --> Finish"]
#[doc= "  state C_AccountValidation <<choice>>"]
#[doc= "  AccountValidation --> C_AccountValidation: validate_accounts"]
#[doc= "  C_AccountValidation --> Error"]
#[doc= "  C_AccountValidation --> Valid"]
#[doc= "```"]
const LOGIN: &'static str = "login";
```

image

But using the current version I get this:

image

If you're wondering why I am using `#[doc="..."]`:
- I need to `quote!` the docs like this
- I tried with `///` and the same thing happened

Any idea what the problem might be? I'd be more than glad to help since this is a valuable feature for my crate but I'd need some guidance.

### PR DESCRIPTION
**Pull request by jmg-duarte**
This fixes issue #11.

I am now able to correctly render the docs, even from my macro.
image

### CODE REVIEW

**Comment by mersinvald** [comment]
Hi José, thanks for finding the issue and submitting the fix :)

I will see if that's possible to make dependabot watch for new versions of mermaid.js

**Comment by jmg-duarte** [comment]
Are you going to release 0.1.9 soon? I'm currently dependent on my branch and would like to migrate the project to depend solely on yours

**Comment by mersinvald** [comment]
Yes, as soon as I'm in the office

**Comment by mersinvald** [comment]
@jmg-duarte the `0.1.9` is now live, thanks again for submitting the fix! 😊

**Pull request merged**
