### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by vorot93**

### CODE REVIEW

**Comment by mersinvald** [comment]
Hi, as discussed in #21, I don't find MSRV bump justified with itertools upgrade, after getting a look at the 0.10 changelog.

What's the reason to update pretty_assertions?

**Comment by vorot93** [comment]
Monomorphization of downstream dependencies.

**Comment by vorot93** [comment]
Deduplication of dependencies when used downstream.

**Comment by mersinvald** [comment]
Fixed in [0.3.0](https://github.com/mersinvald/aquamarine/releases/tag/v0.3.0)

**Pull request closed without merging**
